project_id = "qfxustvmwdyjduzpeafk"

[functions.transcribe-audio]
verify_jwt = false

[functions.transcribe-elevenlabs]
verify_jwt = false

[functions.upload-recording]
verify_jwt = false

[functions.register-recording]
verify_jwt = false

[functions.get-upload-url]
verify_jwt = false

[functions.get-recordings]
verify_jwt = false

[functions.get-topics]
verify_jwt = false

[functions.get-languages]
verify_jwt = false

[functions.process-audio]
verify_jwt = false
