project_id = "qfxustvmwdyjduzpeafk"

[functions.transcribe-audio]
verify_jwt = false

[functions.upload-recording]
verify_jwt = false

[functions.get-recordings]
verify_jwt = false

[functions.get-topics]
verify_jwt = false

[functions.get-languages]
verify_jwt = false
